//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sqr.SSO.Application.SsoWcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Sqr.DC.EF.Models")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BizCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BizCode {
            get {
                return this.BizCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BizCodeField, value) != true)) {
                    this.BizCodeField = value;
                    this.RaisePropertyChanged("BizCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreateId {
            get {
                return this.CreateIdField;
            }
            set {
                if ((this.CreateIdField.Equals(value) != true)) {
                    this.CreateIdField = value;
                    this.RaisePropertyChanged("CreateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SsoSite", Namespace="http://schemas.datacontract.org/2004/07/Sqr.DC.EF.Models")]
    [System.SerializableAttribute()]
    public partial class SsoSite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AddTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SetCookieUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AddTime {
            get {
                return this.AddTimeField;
            }
            set {
                if ((this.AddTimeField.Equals(value) != true)) {
                    this.AddTimeField = value;
                    this.RaisePropertyChanged("AddTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChName {
            get {
                return this.ChNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ChNameField, value) != true)) {
                    this.ChNameField = value;
                    this.RaisePropertyChanged("ChName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnName {
            get {
                return this.EnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EnNameField, value) != true)) {
                    this.EnNameField = value;
                    this.RaisePropertyChanged("EnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SetCookieUrl {
            get {
                return this.SetCookieUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SetCookieUrlField, value) != true)) {
                    this.SetCookieUrlField = value;
                    this.RaisePropertyChanged("SetCookieUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SsoWcfService.ISsoService")]
    public interface ISsoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISsoService/GetUser", ReplyAction="http://tempuri.org/ISsoService/GetUserResponse")]
        Sqr.SSO.Application.SsoWcfService.User GetUser(string account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISsoService/GetUser", ReplyAction="http://tempuri.org/ISsoService/GetUserResponse")]
        System.Threading.Tasks.Task<Sqr.SSO.Application.SsoWcfService.User> GetUserAsync(string account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISsoService/ValidAndGet", ReplyAction="http://tempuri.org/ISsoService/ValidAndGetResponse")]
        Sqr.SSO.Application.SsoWcfService.User ValidAndGet(string account, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISsoService/ValidAndGet", ReplyAction="http://tempuri.org/ISsoService/ValidAndGetResponse")]
        System.Threading.Tasks.Task<Sqr.SSO.Application.SsoWcfService.User> ValidAndGetAsync(string account, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISsoService/GetSsoSiteList", ReplyAction="http://tempuri.org/ISsoService/GetSsoSiteListResponse")]
        System.Collections.Generic.List<Sqr.SSO.Application.SsoWcfService.SsoSite> GetSsoSiteList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISsoService/GetSsoSiteList", ReplyAction="http://tempuri.org/ISsoService/GetSsoSiteListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Sqr.SSO.Application.SsoWcfService.SsoSite>> GetSsoSiteListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISsoServiceChannel : Sqr.SSO.Application.SsoWcfService.ISsoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SsoServiceClient : System.ServiceModel.ClientBase<Sqr.SSO.Application.SsoWcfService.ISsoService>, Sqr.SSO.Application.SsoWcfService.ISsoService {
        
        public SsoServiceClient() {
        }
        
        public SsoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SsoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SsoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SsoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sqr.SSO.Application.SsoWcfService.User GetUser(string account) {
            return base.Channel.GetUser(account);
        }
        
        public System.Threading.Tasks.Task<Sqr.SSO.Application.SsoWcfService.User> GetUserAsync(string account) {
            return base.Channel.GetUserAsync(account);
        }
        
        public Sqr.SSO.Application.SsoWcfService.User ValidAndGet(string account, string password) {
            return base.Channel.ValidAndGet(account, password);
        }
        
        public System.Threading.Tasks.Task<Sqr.SSO.Application.SsoWcfService.User> ValidAndGetAsync(string account, string password) {
            return base.Channel.ValidAndGetAsync(account, password);
        }
        
        public System.Collections.Generic.List<Sqr.SSO.Application.SsoWcfService.SsoSite> GetSsoSiteList() {
            return base.Channel.GetSsoSiteList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Sqr.SSO.Application.SsoWcfService.SsoSite>> GetSsoSiteListAsync() {
            return base.Channel.GetSsoSiteListAsync();
        }
    }
}
