//-----------------------------------------------------------------------
// <copyright file=" Accounts.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: Accounts.cs
// * history : Created by T4 10/28/2018 21:39:12 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.Data.Entity.ModelConfiguration;
using Sqr.DC.EF.Models;


namespace Sqr.DC.EF.Configs
{
    /// <summary>
    /// accounts Entity Model Config
    /// </summary>   
    public class AccountsConfig :EntityTypeConfiguration<Accounts>
    {
		public AccountsConfig()
        {
            ToTable("accounts");

            HasKey(m => m.Id).Property(m => m.Id).HasColumnType("bigint");
        
	        
			/// <summary>
			/// 主键
			/// </summary>
			Property(m=>m.Id).HasColumnName("Id").HasColumnType("bigint").IsRequired();
	        
			/// <summary>
			/// 登入账号
			/// </summary>
			Property(m=>m.LoginAccount).HasColumnName("Login_Account").HasColumnType("varchar").HasMaxLength(50).IsRequired();
	        
			/// <summary>
			/// 登入密码
			/// </summary>
			Property(m=>m.LoginPassword).HasColumnName("Login_Password").HasColumnType("varchar").HasMaxLength(50).IsRequired();
	        
			/// <summary>
			/// 登入名称
			/// </summary>
			Property(m=>m.LoginName).HasColumnName("Login_Name").HasColumnType("varchar").HasMaxLength(50).IsRequired();
	        
			/// <summary>
			/// 邮箱地址
			/// </summary>
			Property(m=>m.Email).HasColumnName("Email").HasColumnType("varchar").HasMaxLength(100).IsRequired();
	        
			/// <summary>
			/// 是否删除
			/// </summary>
			Property(m=>m.IsDeleted).HasColumnName("Is_Deleted").HasColumnType("binary").IsRequired();
	        
			/// <summary>
			/// 删除时间
			/// </summary>
			Property(m=>m.DeleteTime).HasColumnName("Delete_Time").HasColumnType("datetime");
	        
			/// <summary>
			/// 创建时间
			/// </summary>
			Property(m=>m.CreateTime).HasColumnName("Create_Time").HasColumnType("datetime").IsRequired();
	        
			/// <summary>
			/// 更新时间
			/// </summary>
			Property(m=>m.UpdateTime).HasColumnName("Update_Time").HasColumnType("datetime").IsRequired();
			}
	}
}
