//-----------------------------------------------------------------------
// <copyright file=" ActionInfo.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: ActionInfo.cs
// * history : Created by T4 10/29/2018 21:39:19 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.Data.Entity.ModelConfiguration;
using Sqr.DC.EF.Models;


namespace Sqr.DC.EF.Configs
{
    /// <summary>
    /// action_info Entity Model Config
    /// </summary>   
    public class ActionInfoConfig :EntityTypeConfiguration<ActionInfo>
    {
		public ActionInfoConfig()
        {
            ToTable("action_info");

            HasKey(m => m.Id).Property(m => m.Id).HasColumnType("bigint");
        
	        
			/// <summary>
			/// 主键
			/// </summary>
			Property(m=>m.Id).HasColumnName("Id").HasColumnType("bigint").IsRequired();
	        
			/// <summary>
			/// 名称
			/// </summary>
			Property(m=>m.Name).HasColumnName("Name").HasColumnType("varchar").HasMaxLength(50).IsRequired();
	        
			/// <summary>
			/// Controller
			/// </summary>
			Property(m=>m.Controller).HasColumnName("Controller").HasColumnType("varchar").HasMaxLength(50).IsRequired();
	        
			/// <summary>
			/// Action
			/// </summary>
			Property(m=>m.Action).HasColumnName("Action").HasColumnType("varchar").HasMaxLength(50).IsRequired();
	        
			/// <summary>
			/// 地址参数
			/// </summary>
			Property(m=>m.Parameters).HasColumnName("Parameters").HasColumnType("varchar").HasMaxLength(100);
	        
			/// <summary>
			/// 类型（1：分类，2：菜单，3：动作）
			/// </summary>
			Property(m=>m.Category).HasColumnName("Category").HasColumnType("smallint").IsRequired();
	        
			/// <summary>
			/// 邮箱地址
			/// </summary>
			Property(m=>m.ParentId).HasColumnName("Parent_Id").HasColumnType("bigint");
	        
			/// <summary>
			/// 是否删除
			/// </summary>
			Property(m=>m.IsDeleted).HasColumnName("Is_Deleted").HasColumnType("tinyint").IsRequired();
	        
			/// <summary>
			/// 删除时间
			/// </summary>
			Property(m=>m.DeleteTime).HasColumnName("Delete_Time").HasColumnType("datetime");
	        
			/// <summary>
			/// 创建时间
			/// </summary>
			Property(m=>m.CreateTime).HasColumnName("Create_Time").HasColumnType("datetime").IsRequired();
	        
			/// <summary>
			/// 更新时间
			/// </summary>
			Property(m=>m.UpdateTime).HasColumnName("Update_Time").HasColumnType("datetime").IsRequired();
			}
	}
}
