//-----------------------------------------------------------------------
// <copyright file=" BannerInfo.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: BannerInfo.cs
// * history : Created by T4 10/29/2018 21:39:19 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.Data.Entity.ModelConfiguration;
using Sqr.DC.EF.Models;


namespace Sqr.DC.EF.Configs
{
    /// <summary>
    /// banner_info Entity Model Config
    /// </summary>   
    public class BannerInfoConfig :EntityTypeConfiguration<BannerInfo>
    {
		public BannerInfoConfig()
        {
            ToTable("banner_info");

            HasKey(m => m.Id).Property(m => m.Id).HasColumnType("bigint");
        
	        
			/// <summary>
			/// 主键
			/// </summary>
			Property(m=>m.Id).HasColumnName("Id").HasColumnType("bigint").IsRequired();
	        
			/// <summary>
			/// 标题
			/// </summary>
			Property(m=>m.Title).HasColumnName("Title").HasColumnType("varchar").HasMaxLength(100).IsRequired();
	        
			/// <summary>
			/// 链接地址
			/// </summary>
			Property(m=>m.Linkurl).HasColumnName("LinkUrl").HasColumnType("varchar").HasMaxLength(100).IsRequired();
	        
			/// <summary>
			/// 链接方式
			/// </summary>
			Property(m=>m.Linktype).HasColumnName("LinkType").HasColumnType("varchar").HasMaxLength(10).IsRequired();
	        
			/// <summary>
			/// 图片地址
			/// </summary>
			Property(m=>m.Imageurl).HasColumnName("ImageUrl").HasColumnType("varchar").HasMaxLength(100).IsRequired();
	        
			/// <summary>
			/// 大图
			/// </summary>
			Property(m=>m.Imagebig).HasColumnName("ImageBig").HasColumnType("varchar").HasMaxLength(100).IsRequired();
	        
			/// <summary>
			/// 发布时间
			/// </summary>
			Property(m=>m.PublishedTime).HasColumnName("Published_Time").HasColumnType("datetime");
	        
			/// <summary>
			/// 状态：1发布，2不发布
			/// </summary>
			Property(m=>m.Ispublished).HasColumnName("IsPublished").HasColumnType("tinyint").IsRequired();
	        
			/// <summary>
			/// 是否删除
			/// </summary>
			Property(m=>m.IsDeleted).HasColumnName("Is_Deleted").HasColumnType("tinyint").IsRequired();
	        
			/// <summary>
			/// 删除时间
			/// </summary>
			Property(m=>m.DeleteTime).HasColumnName("Delete_Time").HasColumnType("datetime");
	        
			/// <summary>
			/// 创建时间
			/// </summary>
			Property(m=>m.CreateTime).HasColumnName("Create_Time").HasColumnType("datetime").IsRequired();
	        
			/// <summary>
			/// 更新时间
			/// </summary>
			Property(m=>m.UpdateTime).HasColumnName("Update_Time").HasColumnType("datetime").IsRequired();
			}
	}
}
