//-----------------------------------------------------------------------
// <copyright file=" NewsInfo.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: NewsInfo.cs
// * history : Created by T4 10/28/2018 21:39:12 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.Data.Entity.ModelConfiguration;
using Sqr.DC.EF.Models;


namespace Sqr.DC.EF.Configs
{
    /// <summary>
    /// news_info Entity Model Config
    /// </summary>   
    public class NewsInfoConfig :EntityTypeConfiguration<NewsInfo>
    {
		public NewsInfoConfig()
        {
            ToTable("news_info");

            HasKey(m => m.Id).Property(m => m.Id).HasColumnType("bigint");
        
	        
			/// <summary>
			/// 主键
			/// </summary>
			Property(m=>m.Id).HasColumnName("Id").HasColumnType("bigint").IsRequired();
	        
			/// <summary>
			/// 标题
			/// </summary>
			Property(m=>m.Title).HasColumnName("Title").HasColumnType("varchar").HasMaxLength(100).IsRequired();
	        
			/// <summary>
			/// 标题2
			/// </summary>
			Property(m=>m.Title2).HasColumnName("Title2").HasColumnType("varchar").HasMaxLength(100).IsRequired();
	        
			/// <summary>
			/// 内容
			/// </summary>
			Property(m=>m.Content).HasColumnName("Content").HasColumnType("varchar").HasMaxLength(5000).IsRequired();
	        
			/// <summary>
			/// 内容2
			/// </summary>
			Property(m=>m.Content2).HasColumnName("Content2").HasColumnType("varchar").HasMaxLength(1000).IsRequired();
	        
			/// <summary>
			/// 小图
			/// </summary>
			Property(m=>m.Imagesmall).HasColumnName("ImageSmall").HasColumnType("varchar").HasMaxLength(100).IsRequired();
	        
			/// <summary>
			/// 大图
			/// </summary>
			Property(m=>m.Imagebig).HasColumnName("ImageBig").HasColumnType("varchar").HasMaxLength(100).IsRequired();
	        
			/// <summary>
			/// 是否置顶
			/// </summary>
			Property(m=>m.Ishot).HasColumnName("IsHot").HasColumnType("bit").IsRequired();
	        
			/// <summary>
			/// 是否是叶节点
			/// </summary>
			Property(m=>m.Isleaf).HasColumnName("IsLeaf").HasColumnType("bit").IsRequired();
	        
			/// <summary>
			/// 发布时间
			/// </summary>
			Property(m=>m.PublishedTime).HasColumnName("Published_Time").HasColumnType("datetime");
	        
			/// <summary>
			/// 状态：1发布，2不发布
			/// </summary>
			Property(m=>m.Ispublished).HasColumnName("IsPublished").HasColumnType("tinyint").IsRequired();
	        
			/// <summary>
			/// 是否删除
			/// </summary>
			Property(m=>m.IsDeleted).HasColumnName("Is_Deleted").HasColumnType("tinyint").IsRequired();
	        
			/// <summary>
			/// 删除时间
			/// </summary>
			Property(m=>m.DeleteTime).HasColumnName("Delete_Time").HasColumnType("datetime");
	        
			/// <summary>
			/// 创建时间
			/// </summary>
			Property(m=>m.CreateTime).HasColumnName("Create_Time").HasColumnType("datetime").IsRequired();
	        
			/// <summary>
			/// 更新时间
			/// </summary>
			Property(m=>m.UpdateTime).HasColumnName("Update_Time").HasColumnType("datetime").IsRequired();
			}
	}
}
