//-----------------------------------------------------------------------
// <copyright file=" account_roles_relation.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: AccountRolesRelation.cs
// * history : Created by T4 10/19/2018 21:54:09 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

namespace Sqr.DC.EF.Models
{
    /// <summary>
    /// AccountRolesRelation Entity Model
    /// </summary>    
    [Serializable]
    [DataContract]
    public class AccountRolesRelation:BaseMo
    {
      
			/// <summary>
			/// 账号ID
			/// </summary>
								[DataMember]
						public long AccountId { get; set; }

      
			/// <summary>
			/// 角色ID
			/// </summary>
								[DataMember]
						public long RoleId { get; set; }

    }
}
