//-----------------------------------------------------------------------
// <copyright file=" key_value_info.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: KeyValueInfo.cs
// * history : Created by T4 10/29/2018 21:39:04 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Sqr.DC.EF.Models
{
    /// <summary>
    /// KeyValueInfo Entity Model
    /// </summary>    
    [Serializable]
    public class KeyValueInfo:BaseMo
    {
      
			/// <summary>
			/// 编码
			/// </summary>
						public string Code { get; set; }

      
			/// <summary>
			/// 值
			/// </summary>
						public string Value { get; set; }

      
			/// <summary>
			/// 备注
			/// </summary>
						public string Remark { get; set; }

    }
}
