//-----------------------------------------------------------------------
// <copyright file=" news_category.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: NewsCategory.cs
// * history : Created by T4 10/19/2018 21:54:09 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

namespace Sqr.DC.EF.Models
{
    /// <summary>
    /// NewsCategory Entity Model
    /// </summary>    
    [Serializable]
    [DataContract]
    public class NewsCategory:BaseMo
    {
      
			/// <summary>
			/// 标题
			/// </summary>
								[DataMember]
						public string Name { get; set; }

      
			/// <summary>
			/// 父ID
			/// </summary>
								[DataMember]
						public long ParentId { get; set; }

    }
}
