//-----------------------------------------------------------------------
// <copyright file=" product_category.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: ProductCategory.cs
// * history : Created by T4 10/29/2018 21:39:04 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Sqr.DC.EF.Models
{
    /// <summary>
    /// ProductCategory Entity Model
    /// </summary>    
    [Serializable]
    public class ProductCategory:BaseMo
    {
      
			/// <summary>
			/// 标题
			/// </summary>
						public string Name { get; set; }

      
			/// <summary>
			/// 父ID
			/// </summary>
						public long ParentId { get; set; }

    }
}
