//-----------------------------------------------------------------------
// <copyright file=" roles.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: Roles.cs
// * history : Created by T4 10/19/2018 21:54:09 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

namespace Sqr.DC.EF.Models
{
    /// <summary>
    /// Roles Entity Model
    /// </summary>    
    [Serializable]
    [DataContract]
    public class Roles:BaseMo
    {
      
			/// <summary>
			/// 名称
			/// </summary>
								[DataMember]
						public string Rolename { get; set; }

    }
}
