//-----------------------------------------------------------------------
// <copyright file=" sso_sites.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: SsoSites.cs
// * history : Created by T4 10/19/2018 21:54:09 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

namespace Sqr.DC.EF.Models
{
    /// <summary>
    /// SsoSites Entity Model
    /// </summary>    
    [Serializable]
    [DataContract]
    public class SsoSites:BaseMo
    {
      
			/// <summary>
			/// 站点名称
			/// </summary>
								[DataMember]
						public string SiteName { get; set; }

      
			/// <summary>
			/// 站点域名
			/// </summary>
								[DataMember]
						public string SiteUrl { get; set; }

      
			/// <summary>
			/// 登入地址
			/// </summary>
								[DataMember]
						public string SiteLoginUrl { get; set; }

      
			/// <summary>
			/// 登出地址
			/// </summary>
								[DataMember]
						public string SiteLogoutUrl { get; set; }

    }
}
