//-----------------------------------------------------------------------
// <copyright file=" User.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: User.cs
// * history : Created by T4 02/23/2018 11:40:12 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

namespace Sqr.DC.EF.Models
{
    /// <summary>
    /// User Entity Model
    /// </summary>    
    [Serializable]
    [DataContract]
    public class User
    {
        /// <summary>
        /// 主键
        /// </summary>
        [DataMember]
        public int Id { get; set; }
    
        /// <summary>
        /// 账号
        /// </summary>
        [DataMember]
        public string Account { get; set; }
    
        /// <summary>
        /// 密码
        /// </summary>
        [DataMember]
        public string Password { get; set; }
    
        /// <summary>
        /// 昵称
        /// </summary>
        [DataMember]
        public string NickName { get; set; }
    
        /// <summary>
        /// 性别
        /// </summary>
        [DataMember]
        public int Gender { get; set; }
    
        /// <summary>
        /// 状态：1正常，2无效
        /// </summary>
        [DataMember]
        public int Status { get; set; }
    
        /// <summary>
        /// 类型：1客户，2员工
        /// </summary>
        [DataMember]
        public int Type { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember]
        public string BizCode { get; set; }
    
        /// <summary>
        /// 电子邮件
        /// </summary>
        [DataMember]
        public string EMail { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember]
        public DateTime CreateTime { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember]
        public int CreateId { get; set; }
    }
}
