//-----------------------------------------------------------------------
// <copyright file=" v_account_actioninfo.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: VAccountActioninfo.cs
// * history : Created by T4 10/29/2018 21:39:04 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Sqr.DC.EF.Models
{
    /// <summary>
    /// VAccountActioninfo Entity Model
    /// </summary>    
    [Serializable]
    public class VAccountActioninfo:BaseMo
    {
      
			/// <summary>
			/// 
			/// </summary>
						public long AccountId { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Name { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Controller { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Action { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Parameters { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public short Category { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public long ParentId { get; set; }

        public string SystemId { get; set; }

    }
}
