//-----------------------------------------------------------------------
// <copyright file=" v_account_actioninfo.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: VAccountActioninfo.cs
// * history : Created by T4 10/28/2018 21:44:15 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

namespace Sqr.DC.EF.Models
{
    /// <summary>
    /// VAccountActioninfo Entity Model
    /// </summary>    
    [Serializable]
    [DataContract]
    public class VAccountActioninfo:BaseMo
    {
      
			/// <summary>
			/// 
			/// </summary>
								[DataMember]
						public long AccountId { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
								[DataMember]
						public string Name { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
								[DataMember]
						public string Controller { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
								[DataMember]
						public string Action { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
								[DataMember]
						public string Parameters { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
								[DataMember]
						public int Category { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
								[DataMember]
						public long ParentId { get; set; }

    }
}
