//-----------------------------------------------------------------------
// <copyright file=" actioninfo.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: Actioninfo.cs
// * history : Created by T4 03/11/2019 21:14:56 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Sqr.DC.Entities
{
    /// <summary>
    /// Actioninfo Entity Model
    /// </summary>    
    public class ActionInfo:BaseMo
    {
      
			/// <summary>
			/// 
			/// </summary>
						public string Action { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Category { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Controller { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Name { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Parameters { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public int Parentid { get; set; }

    }
}
