//-----------------------------------------------------------------------
// <copyright file=" ssosites.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: Ssosites.cs
// * history : Created by T4 03/11/2019 21:14:56 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Sqr.DC.Entities
{
    /// <summary>
    /// Ssosites Entity Model
    /// </summary>    
    public class SsoSites:BaseMo
    {
      
			/// <summary>
			/// 
			/// </summary>
						public string Sitecode { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Siteloginurl { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Sitelogouturl { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Sitename { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Siteurl { get; set; }

    }
}
