//-----------------------------------------------------------------------
// <copyright file=" useractionrelation.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: Useractionrelation.cs
// * history : Created by T4 03/11/2019 21:14:56 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Sqr.DC.Entities
{
    /// <summary>
    /// Useractionrelation Entity Model
    /// </summary>    
    public class Useractionrelation:BaseMo
    {
      
			/// <summary>
			/// 
			/// </summary>
						public int Actionid { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public int Userid { get; set; }

    }
}
