//-----------------------------------------------------------------------
// <copyright file=" SsoSitesBusiness.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: SsoSitesBusiness.cs
// * history : Created by T4 09/16/2018 14:31:24 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.Common;
using Sqr.DC.Entities;
using Sqr.DC.Repositories;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Sqr.DC.Services
{
    /// <summary>
    /// sso_sites Respository
    /// </summary>   
    public partial class SsoSitesService : ServiceBase<SsoSitesService>
    {
        public async Task<IList<SsoSites>> GetSSOSites()
        {
            return await new SsoSitesRepository().GetAllAsync();
        }

    }
}
