//-----------------------------------------------------------------------
// <copyright file=" keyvalueinfo.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: Keyvalueinfo.cs
// * history : Created by T4 03/11/2019 21:14:56 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Sqr.DC.Entities
{
    /// <summary>
    /// Keyvalueinfo Entity Model
    /// </summary>    
    public class Keyvalueinfo:BaseMo
    {
      
			/// <summary>
			/// 
			/// </summary>
						public string Code { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Remark { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Value { get; set; }

    }
}
