//-----------------------------------------------------------------------
// <copyright file=" newsinfo.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: Newsinfo.cs
// * history : Created by T4 03/11/2019 21:14:56 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Sqr.DC.Entities
{
    /// <summary>
    /// Newsinfo Entity Model
    /// </summary>    
    public class Newsinfo:BaseMo
    {
      
			/// <summary>
			/// 
			/// </summary>
						public string Content { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Content2 { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Imagebig { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Imagesmall { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Ishot { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Ispublished { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public DateTime Publishedtime { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Title { get; set; }

      
			/// <summary>
			/// 
			/// </summary>
						public string Title2 { get; set; }

    }
}
