//-----------------------------------------------------------------------
// <copyright file=" productinfo.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: Productinfo.cs
// * history : Created by T4 03/11/2019 21:14:56 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Sqr.DC.Entities
{
    /// <summary>
    /// Productinfo Entity Model
    /// </summary>    
    public class Productinfo : BaseMo
    {

        /// <summary>
        /// 
        /// </summary>
        public string Content { get; set; }



        /// <summary>
        /// 
        /// </summary>
        public string Imagebig { get; set; }


        /// <summary>
        /// 
        /// </summary>
        public string Imagesmall { get; set; }



        /// <summary>
        /// 
        /// </summary>
        public string Name { get; set; }


        /// <summary>
        /// 
        /// </summary>
        public string Model { get; set; }

        public long Category { get; set; }

    }
}
