//-----------------------------------------------------------------------
// <copyright file=" roles.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: Roles.cs
// * history : Created by T4 03/11/2019 21:14:56 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Sqr.DC.Entities
{
    /// <summary>
    /// Roles Entity Model
    /// </summary>    
    public class Roles : BaseMo
    {

        /// <summary>
        /// 
        /// </summary>
        public string Name { get; set; }

    }
}
