//-----------------------------------------------------------------------
// <copyright file=" userrolesrelation.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: Userrolesrelation.cs
// * history : Created by T4 03/11/2019 21:14:56 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Sqr.DC.Entities
{
    /// <summary>
    /// Userrolesrelation Entity Model
    /// </summary>    
    public class Userrolesrelation : BaseMo
    {

        /// <summary>
        /// 
        /// </summary>
        public long RoleId { get; set; }


        /// <summary>
        /// 
        /// </summary>
        public long UserId { get; set; }

    }
}
