//-----------------------------------------------------------------------
// <copyright file=" ActioninfoRespository.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: ActioninfoRespository.cs
// * history : Created by T4 03/11/2019 21:17:49 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.DC.Entities;
using System;
using System.Threading.Tasks;

namespace Sqr.DC.Repositories
{
    /// <summary>
    /// actioninfo Respository
    /// </summary>   
    public partial class ActioninfoRepository :BaseRepository<ActioninfoRepository,  ActionInfo>
    {
        public async Task<int> DeleteIncludeSub(ActionInfo input)
        {
            return await UpdateAsync<ActionInfo>(c=>new { IsDeleted=1,DeleteTime=DateTime.Now,DeleteUser=input.DeleteUser }, c => c.Id == input.Id || c.ParentId == input.Id);
        }
		
	}
}
