//-----------------------------------------------------------------------
// <copyright file=" ActioninforolesrelationRespository.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: ActioninforolesrelationRespository.cs
// * history : Created by T4 03/11/2019 21:19:09 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.DC.Entities;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Sqr.DC.Repositories
{
    /// <summary>
    /// actioninforolesrelation Respository
    /// </summary>   
    public partial class ActioninforolesrelationRepository :BaseRepository<ActioninforolesrelationRepository, Actioninforolesrelation>
    {
		public async Task<IList<Actioninforolesrelation>> GetByRoleId(long roleId)
        {
            return await QueryListAsync<Actioninforolesrelation>(c => c.Roleid == roleId && c.IsDeleted == 0);
        }

        public async Task<int> RemoveByRoleId(long roleId)
        {
            return await RemoveAsync(c => c.Roleid == roleId);
        }
	}
}
