//-----------------------------------------------------------------------
// <copyright file=" NewscategoryRespository.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: NewscategoryRespository.cs
// * history : Created by T4 03/11/2019 21:17:49 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.DC.Entities;


namespace Sqr.DC.Repositories
{
    /// <summary>
    /// newscategory Respository
    /// </summary>   
    public partial class NewscategoryRepository :BaseRepository<NewscategoryRepository, Newscategory>
    {
		
	}
}
