//-----------------------------------------------------------------------
// <copyright file=" SsositesRespository.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: SsositesRespository.cs
// * history : Created by T4 03/11/2019 21:19:09 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.Dapper.Linq.Common;
using Sqr.DC.Entities;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Sqr.DC.Repositories
{
    /// <summary>
    /// ssosites Respository
    /// </summary>   
    public partial class SsoSitesRepository :BaseRepository<SsoSites>
    {
		public SsoSites GetBySiteCode(string siteCode)
        {
            return QuerySingleOrDefault<SsoSites>(w => w.IsDeleted == 0 && w.Sitecode == siteCode);
        }

        public PagedList<SsoSites> GetPaged(int pageIndex,int pageSize)
        {
            return GetPaged(c => true, new PagedQueryParams() { PageIndex = pageIndex, PageSize = pageSize });
        }

        public async Task<IList<SsoSites>> GetAllAsync()
        {
            return await GetListAsync(c=>1==1);
        }
	}
}
