//-----------------------------------------------------------------------
// <copyright file=" UsersRespository.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: UsersRespository.cs
// * history : Created by T4 03/11/2019 21:19:09 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.DC.Entities;
using System.Threading.Tasks;

namespace Sqr.DC.Repositories
{
    /// <summary>
    /// users Respository
    /// </summary>   
    public partial class UsersRepository :BaseRepository<UsersRepository,  Users>
    {
		public async Task<Users> GetByAccoutAsync(string account)
        {
            return await GetSingleOrDefaultAsync(c => c.Account == account && c.IsDeleted == 0);
        }

        public int UpdatePwd(Users entity)
        {
            return Update(c => new { c.Password }, w => w.Id == entity.Id);
        }
	}
}
