//-----------------------------------------------------------------------
// <copyright file=" ActionInfoRolesRelationRespository.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: ActionInfoRolesRelationRespository.cs
// * history : Created by T4 10/28/2018 21:24:50 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.DC.EF.Models;


namespace Sqr.DC.EF.Repositories
{
    /// <summary>
    /// action_info_roles_relation Respository
    /// </summary>   
    public partial class ActionInfoRolesRelationRepository :BaseRepository<  ActionInfoRolesRelation>
    {
		
	}
}
