//-----------------------------------------------------------------------
// <copyright file=" KeyValueInfoRespository.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: KeyValueInfoRespository.cs
// * history : Created by T4 10/28/2018 21:42:24 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.DC.EF.Models;


namespace Sqr.DC.EF.Repositories
{
    /// <summary>
    /// key_value_info Respository
    /// </summary>   
    public partial class KeyValueInfoRepository :BaseRepository<  KeyValueInfo>
    {
		
	}
}
