//-----------------------------------------------------------------------
// <copyright file=" NewsInfoRespository.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: NewsInfoRespository.cs
// * history : Created by T4 10/28/2018 14:34:48 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.DC.EF.Models;


namespace Sqr.DC.EF.Repositories
{
    /// <summary>
    /// news_info Respository
    /// </summary>   
    public partial class NewsInfoRepository :BaseRepository<  NewsInfo>
    {
		
	}
}
