//-----------------------------------------------------------------------
// <copyright file=" NewsCategoryRespository.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: NewsCategoryRespository.cs
// * history : Created by T4 09/15/2018 22:40:28 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.DC.EF.Models;


namespace Sqr.DC.EF.Repositories
{
    /// <summary>
    /// news_category Respository
    /// </summary>   
    public partial class NewsCategoryRepository :BaseRepository<  NewsCategory>
    {
		
	}
}
