//-----------------------------------------------------------------------
// <copyright file=" SsoSitesRespository.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: SsoSitesRespository.cs
// * history : Created by T4 10/28/2018 21:42:24 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.DC.EF.Models;


namespace Sqr.DC.EF.Repositories
{
    /// <summary>
    /// sso_sites Respository
    /// </summary>   
    public partial class SsoSitesRepository :BaseRepository<  SsoSites>
    {
		
	}
}
