//-----------------------------------------------------------------------
// <copyright file=" ActionInfoBusiness.Generated.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: ActionInfoBusiness.cs
// * history : Created by T4 10/13/2018 17:38:57 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.Common;
using Sqr.Common.Paging;
using Sqr.DC.BLL.Security.DTO;
using Sqr.DC.EF.Models;
using Sqr.DC.EF.Repositories;
using System.Collections.Generic;
using Sqr.Common.IOC;

namespace Sqr.DC.Business
{
    /// <summary>
    /// action_info Respository
    /// </summary>   
    public partial class ActionInfoBusiness :BaseBusiness
    {
		
        public PagingOutput<ActionInfo> GetPageList(PagingInput input)
        {
            return AutofacConfig.Resolve<ActionInfoRepository>().GetPageList(
                input.PageIndex,
                input.PageSize,
                null,
                a => a.CreateTime,
                true
            );
        }

        public List<ActionInfo> GeList()
        {
            return AutofacConfig.Resolve<ActionInfoRepository>().GetAll();
        }

        public ActionInfo GetById(long id)
        {
            return AutofacConfig.Resolve<ActionInfoRepository>().GetById(id);
        }

        public long Add(ActionInfo model)
        {
            model.Id = IdHelper.GetNewId();
            if (AutofacConfig.Resolve<ActionInfoRepository>().Add(model) > 0)
                return model.Id;
            return 0;
        }

        public int Add(List<ActionInfo> models)
        {
            models.ForEach(c => c.Id = IdHelper.GetNewId());
            return AutofacConfig.Resolve<ActionInfoRepository>().Add(models);
        }

        public bool Update(ActionInfo model)
        {
            return AutofacConfig.Resolve<ActionInfoRepository>().Update(model)>0;
        }

        public int Update(List<ActionInfo> models)
        {
            return AutofacConfig.Resolve<ActionInfoRepository>().Update(models) ;
        }
	}
}
