//-----------------------------------------------------------------------
// <copyright file=" KeyValueInfoBusiness.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: KeyValueInfoBusiness.cs
// * history : Created by T4 09/16/2018 14:31:24 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.Common;
using Sqr.Common.Paging;
using Sqr.DC.BLL.Security.DTO;
using Sqr.DC.EF.Models;
using Sqr.DC.EF.Repositories;
using System.Collections.Generic;


namespace Sqr.DC.Business
{
    /// <summary>
    /// key_value_info Respository
    /// </summary>   
    public partial class KeyValueInfoBusiness :BaseBusiness
    {
	}
}
