//-----------------------------------------------------------------------
// <copyright file=" KeyValueInfoBusiness.Generated.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: KeyValueInfoBusiness.cs
// * history : Created by T4 10/13/2018 17:38:57 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.Common;
using Sqr.Common.Paging;
using Sqr.DC.BLL.Security.DTO;
using Sqr.DC.EF.Models;
using Sqr.DC.EF.Repositories;
using System.Collections.Generic;
using Sqr.Common.IOC;

namespace Sqr.DC.Business
{
    /// <summary>
    /// key_value_info Respository
    /// </summary>   
    public partial class KeyValueInfoBusiness :BaseBusiness
    {
		
        public PagingOutput<KeyValueInfo> GetPageList(PagingInput input)
        {
            return AutofacConfig.Resolve<KeyValueInfoRepository>().GetPageList(
                input.PageIndex,
                input.PageSize,
                null,
                a => a.CreateTime,
                true
            );
        }

        public List<KeyValueInfo> GeList()
        {
            return AutofacConfig.Resolve<KeyValueInfoRepository>().GetMany(null);
        }

        public KeyValueInfo GetById(long id)
        {
            return AutofacConfig.Resolve<KeyValueInfoRepository>().GetById(id);
        }

        public long Add(KeyValueInfo model)
        {
            model.Id = IdHelper.GetNewId();
            if (AutofacConfig.Resolve<KeyValueInfoRepository>().Add(model) > 0)
                return model.Id;
            return 0;
        }

        public int Add(List<KeyValueInfo> models)
        {
            models.ForEach(c => c.Id = IdHelper.GetNewId());
            return AutofacConfig.Resolve<KeyValueInfoRepository>().Add(models);
        }

        public bool Update(KeyValueInfo model)
        {
            return AutofacConfig.Resolve<KeyValueInfoRepository>().Update(model)>0;
        }

        public int Update(List<KeyValueInfo> models)
        {
            return AutofacConfig.Resolve<KeyValueInfoRepository>().Update(models) ;
        }
	}
}
