//-----------------------------------------------------------------------
// <copyright file=" NewsInfoBusiness.Generated.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: NewsInfoBusiness.cs
// * history : Created by T4 10/13/2018 17:38:57 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.Common;
using Sqr.Common.Paging;
using Sqr.DC.BLL.Security.DTO;
using Sqr.DC.EF.Models;
using Sqr.DC.EF.Repositories;
using System.Collections.Generic;
using Sqr.Common.IOC;

namespace Sqr.DC.Business
{
    /// <summary>
    /// news_info Respository
    /// </summary>   
    public partial class NewsInfoBusiness :BaseBusiness
    {
		
        public PagingOutput<NewsInfo> GetPageList(PagingInput input)
        {
            return AutofacConfig.Resolve<NewsInfoRepository>().GetPageList(
                input.PageIndex,
                input.PageSize,
                null,
                a => a.CreateTime,
                true
            );
        }

        public List<NewsInfo> GeList()
        {
            return AutofacConfig.Resolve<NewsInfoRepository>().GetMany(null);
        }

        public NewsInfo GetById(long id)
        {
            return AutofacConfig.Resolve<NewsInfoRepository>().GetById(id);
        }

        public long Add(NewsInfo model)
        {
            model.Id = IdHelper.GetNewId();
            if (AutofacConfig.Resolve<NewsInfoRepository>().Add(model) > 0)
                return model.Id;
            return 0;
        }

        public int Add(List<NewsInfo> models)
        {
            models.ForEach(c => c.Id = IdHelper.GetNewId());
            return AutofacConfig.Resolve<NewsInfoRepository>().Add(models);
        }

        public bool Update(NewsInfo model)
        {
            return AutofacConfig.Resolve<NewsInfoRepository>().Update(model)>0;
        }

        public int Update(List<NewsInfo> models)
        {
            return AutofacConfig.Resolve<NewsInfoRepository>().Update(models) ;
        }
	}
}
