//-----------------------------------------------------------------------
// <copyright file=" AccountActionRelationBusiness.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: AccountActionRelationBusiness.cs
// * history : Created by T4 09/16/2018 14:31:24 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.Common;
using Sqr.Common.Paging;
using Sqr.DC.BLL.Security.DTO;
using Sqr.DC.Entities;
using Sqr.DC.Repositories;
using System.Collections.Generic;


namespace Sqr.DC.Services
{
    /// <summary>
    /// account_action_relation Respository
    /// </summary>   
    public partial class AccountActionRelationBusiness :BaseService
    {
	}
}
