//-----------------------------------------------------------------------
// <copyright file=" AccountRolesRelationBusiness.Generated.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: AccountRolesRelationBusiness.cs
// * history : Created by T4 10/13/2018 17:38:57 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.Common;
using Sqr.Common.Paging;
using Sqr.DC.Entities;
using Sqr.DC.Repositories;
using System.Collections.Generic;
using Sqr.Common.IOC;

namespace Sqr.DC.Services
{
    /// <summary>
    /// account_roles_relation Respository
    /// </summary>   
    public partial class AccountRolesRelationBusiness :BaseService
    {
		
	}
}
