//-----------------------------------------------------------------------
// <copyright file=" ProductInfoBusiness.Generated.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: ProductInfoBusiness.cs
// * history : Created by T4 10/13/2018 17:38:57 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.Common;
using Sqr.Common.Paging;
using Sqr.DC.BLL.Security.DTO;
using Sqr.DC.Entities;
using Sqr.DC.Repositories;
using System.Collections.Generic;
using Sqr.Common.IOC;

namespace Sqr.DC.Services
{
    /// <summary>
    /// product_info Respository
    /// </summary>   
    public partial class ProductInfoBusiness :BaseService
    {
		
        public PagingOutput<ProductInfo> GetPageList(PagingInput input)
        {
            return AutofacConfig.Resolve<ProductInfoRepository>().GetPageList(
                input.PageIndex,
                input.PageSize,
                null,
                a => a.CreateTime,
                true
            );
        }

        public List<ProductInfo> GeList()
        {
            return AutofacConfig.Resolve<ProductInfoRepository>().GetMany(null);
        }

        public ProductInfo GetById(long id)
        {
            return AutofacConfig.Resolve<ProductInfoRepository>().GetById(id);
        }

        public long Add(ProductInfo model)
        {
            model.Id = IdHelper.GetNewId();
            if (AutofacConfig.Resolve<ProductInfoRepository>().Add(model) > 0)
                return model.Id;
            return 0;
        }

        public int Add(List<ProductInfo> models)
        {
            models.ForEach(c => c.Id = IdHelper.GetNewId());
            return AutofacConfig.Resolve<ProductInfoRepository>().Add(models);
        }

        public bool Update(ProductInfo model)
        {
            return AutofacConfig.Resolve<ProductInfoRepository>().Update(model)>0;
        }

        public int Update(List<ProductInfo> models)
        {
            return AutofacConfig.Resolve<ProductInfoRepository>().Update(models) ;
        }
	}
}
