//-----------------------------------------------------------------------
// <copyright file=" ProductCategoryBusiness.Generated.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: ProductCategoryBusiness.cs
// * history : Created by T4 10/13/2018 17:38:57 
// </copyright>
//-----------------------------------------------------------------------
using Sqr.Common;
using Sqr.Common.Paging;
using Sqr.DC.BLL.Security.DTO;
using Sqr.DC.Entities;
using Sqr.DC.Repositories;
using System.Collections.Generic;
using Sqr.Common.IOC;

namespace Sqr.DC.Services
{
    /// <summary>
    /// product_category Respository
    /// </summary>   
    public partial class ProductCategoryBusiness :BaseService
    {
		
        public PagingOutput<ProductCategory> GetPageList(PagingInput input)
        {
            return AutofacConfig.Resolve<ProductCategoryRepository>().GetPageList(
                input.PageIndex,
                input.PageSize,
                null,
                a => a.CreateTime,
                true
            );
        }

        public List<ProductCategory> GeList()
        {
            return AutofacConfig.Resolve<ProductCategoryRepository>().GetMany(null);
        }

        public ProductCategory GetById(long id)
        {
            return AutofacConfig.Resolve<ProductCategoryRepository>().GetById(id);
        }

        public long Add(ProductCategory model)
        {
            model.Id = IdHelper.GetNewId();
            if (AutofacConfig.Resolve<ProductCategoryRepository>().Add(model) > 0)
                return model.Id;
            return 0;
        }

        public int Add(List<ProductCategory> models)
        {
            models.ForEach(c => c.Id = IdHelper.GetNewId());
            return AutofacConfig.Resolve<ProductCategoryRepository>().Add(models);
        }

        public bool Update(ProductCategory model)
        {
            return AutofacConfig.Resolve<ProductCategoryRepository>().Update(model)>0;
        }

        public int Update(List<ProductCategory> models)
        {
            return AutofacConfig.Resolve<ProductCategoryRepository>().Update(models) ;
        }
	}
}
