//-----------------------------------------------------------------------
// <copyright file=" news_category.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: NewsCategory.cs
// * history : Created by T4 10/19/2018 21:39:33 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Sqr.DC.Repository.Core;

namespace Sqr.DC.Repository.Models
{
    /// <summary>
    /// NewsCategory Entity Model
    /// </summary>    
    [Serializable]
    public class NewsCategory:ModelBase
    {
      
			/// <summary>
			/// 标题
			/// </summary>
						public string Name { get; set; }

      
			/// <summary>
			/// 父ID
			/// </summary>
						public int ParentId { get; set; }

    }
}
