//-----------------------------------------------------------------------
// <copyright file=" roles.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: Roles.cs
// * history : Created by T4 10/19/2018 21:39:33 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Sqr.DC.Repository.Core;

namespace Sqr.DC.Repository.Models
{
    /// <summary>
    /// Roles Entity Model
    /// </summary>    
    [Serializable]
    public class Roles:ModelBase
    {
      
			/// <summary>
			/// 名称
			/// </summary>
						public string Rolename { get; set; }

    }
}
